--
-- PostgreSQL database dump
--

-- Dumped from database version 17.3 (Debian 17.3-1.pgdg120+1)
-- Dumped by pg_dump version 17.3 (Debian 17.3-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO comms_admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO comms_admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO comms_admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_action; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_action (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_action OWNER TO comms_admin;

--
-- Name: comms_db_action_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_action ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_action_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_attachement; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_attachement (
    id bigint NOT NULL,
    name character varying,
    description text,
    url character varying(200),
    created_time timestamp with time zone NOT NULL,
    last_modified_time timestamp with time zone NOT NULL,
    content_type_id bigint,
    creator_id bigint NOT NULL,
    submission_id bigint
);


ALTER TABLE public.comms_db_attachement OWNER TO comms_admin;

--
-- Name: comms_db_attachement_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_attachement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_attachement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_compliancerisk; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_compliancerisk (
    id bigint NOT NULL,
    suggested_edits text NOT NULL,
    risk_level_id bigint,
    submission_id bigint NOT NULL
);


ALTER TABLE public.comms_db_compliancerisk OWNER TO comms_admin;

--
-- Name: comms_db_compliancerisk_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_compliancerisk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_compliancerisk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_contenttype; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_contenttype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_contenttype OWNER TO comms_admin;

--
-- Name: comms_db_contenttype_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_contenttype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_contenttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_denialreason; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_denialreason (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_denialreason OWNER TO comms_admin;

--
-- Name: comms_db_denialreason_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_denialreason ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_denialreason_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_distributionchannel; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_distributionchannel (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_distributionchannel OWNER TO comms_admin;

--
-- Name: comms_db_distributionchannel_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_distributionchannel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_distributionchannel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_flexschema; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_flexschema (
    id bigint NOT NULL,
    name character varying NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.comms_db_flexschema OWNER TO comms_admin;

--
-- Name: comms_db_flexschema_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_flexschema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_flexschema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_flexschemafield; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_flexschemafield (
    id bigint NOT NULL,
    required boolean NOT NULL,
    "fieldType" character varying NOT NULL,
    schema_id bigint,
    description character varying,
    extra_data jsonb,
    name character varying NOT NULL
);


ALTER TABLE public.comms_db_flexschemafield OWNER TO comms_admin;

--
-- Name: comms_db_flexschemafield_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_flexschemafield ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_flexschemafield_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_form; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_form (
    id bigint NOT NULL,
    name character varying NOT NULL,
    description text NOT NULL,
    schema_id bigint
);


ALTER TABLE public.comms_db_form OWNER TO comms_admin;

--
-- Name: comms_db_form_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_form ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_industry; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_industry (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_industry OWNER TO comms_admin;

--
-- Name: comms_db_industry_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_industry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_industry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_partner; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_partner (
    id bigint NOT NULL,
    name character varying NOT NULL,
    contact_email character varying(254) NOT NULL,
    industry_id bigint
);


ALTER TABLE public.comms_db_partner OWNER TO comms_admin;

--
-- Name: comms_db_partner_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_partner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_partner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_priority; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_priority (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_priority OWNER TO comms_admin;

--
-- Name: comms_db_priority_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_priority ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_priority_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_review; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_review (
    id bigint NOT NULL,
    sequence integer NOT NULL,
    reviewer_id bigint NOT NULL,
    submission_id bigint
);


ALTER TABLE public.comms_db_review OWNER TO comms_admin;

--
-- Name: comms_db_review_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_risklevel; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_risklevel (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_risklevel OWNER TO comms_admin;

--
-- Name: comms_db_risklevel_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_risklevel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_risklevel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_role; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_role (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_role OWNER TO comms_admin;

--
-- Name: comms_db_role_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_rule; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_rule (
    id bigint NOT NULL,
    name character varying NOT NULL,
    text text NOT NULL
);


ALTER TABLE public.comms_db_rule OWNER TO comms_admin;

--
-- Name: comms_db_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_status; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_status (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.comms_db_status OWNER TO comms_admin;

--
-- Name: comms_db_status_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_submission; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_submission (
    id bigint NOT NULL,
    title character varying,
    flagged boolean NOT NULL,
    flag_reason text,
    data jsonb NOT NULL,
    created_time timestamp with time zone NOT NULL,
    last_modified_time timestamp with time zone NOT NULL,
    content_type_id bigint,
    creator_id bigint NOT NULL,
    industry_id bigint,
    partner_id bigint,
    priority_id bigint,
    schema_id bigint,
    status_id bigint
);


ALTER TABLE public.comms_db_submission OWNER TO comms_admin;

--
-- Name: comms_db_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_thread; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_thread (
    id bigint NOT NULL,
    submission_id bigint NOT NULL
);


ALTER TABLE public.comms_db_thread OWNER TO comms_admin;

--
-- Name: comms_db_thread_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_thread ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_thread_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_threadmessage; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_threadmessage (
    id bigint NOT NULL,
    parent_id integer NOT NULL,
    content text NOT NULL,
    thread_id bigint NOT NULL
);


ALTER TABLE public.comms_db_threadmessage OWNER TO comms_admin;

--
-- Name: comms_db_threadmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_threadmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_threadmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_user; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL
);


ALTER TABLE public.comms_db_user OWNER TO comms_admin;

--
-- Name: comms_db_user_groups; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.comms_db_user_groups OWNER TO comms_admin;

--
-- Name: comms_db_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_user_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comms_db_user_user_permissions; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.comms_db_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.comms_db_user_user_permissions OWNER TO comms_admin;

--
-- Name: comms_db_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.comms_db_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comms_db_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO comms_admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO comms_admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO comms_admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: comms_admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: comms_admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO comms_admin;

--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: comms_db_action comms_db_action_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_action
    ADD CONSTRAINT comms_db_action_name_key UNIQUE (name);


--
-- Name: comms_db_action comms_db_action_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_action
    ADD CONSTRAINT comms_db_action_pkey PRIMARY KEY (id);


--
-- Name: comms_db_attachement comms_db_attachement_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_attachement
    ADD CONSTRAINT comms_db_attachement_pkey PRIMARY KEY (id);


--
-- Name: comms_db_compliancerisk comms_db_compliancerisk_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_compliancerisk
    ADD CONSTRAINT comms_db_compliancerisk_pkey PRIMARY KEY (id);


--
-- Name: comms_db_compliancerisk comms_db_compliancerisk_submission_id_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_compliancerisk
    ADD CONSTRAINT comms_db_compliancerisk_submission_id_key UNIQUE (submission_id);


--
-- Name: comms_db_contenttype comms_db_contenttype_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_contenttype
    ADD CONSTRAINT comms_db_contenttype_name_key UNIQUE (name);


--
-- Name: comms_db_contenttype comms_db_contenttype_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_contenttype
    ADD CONSTRAINT comms_db_contenttype_pkey PRIMARY KEY (id);


--
-- Name: comms_db_denialreason comms_db_denialreason_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_denialreason
    ADD CONSTRAINT comms_db_denialreason_name_key UNIQUE (name);


--
-- Name: comms_db_denialreason comms_db_denialreason_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_denialreason
    ADD CONSTRAINT comms_db_denialreason_pkey PRIMARY KEY (id);


--
-- Name: comms_db_distributionchannel comms_db_distributionchannel_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_distributionchannel
    ADD CONSTRAINT comms_db_distributionchannel_name_key UNIQUE (name);


--
-- Name: comms_db_distributionchannel comms_db_distributionchannel_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_distributionchannel
    ADD CONSTRAINT comms_db_distributionchannel_pkey PRIMARY KEY (id);


--
-- Name: comms_db_flexschema comms_db_flexschema_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_flexschema
    ADD CONSTRAINT comms_db_flexschema_name_key UNIQUE (name);


--
-- Name: comms_db_flexschema comms_db_flexschema_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_flexschema
    ADD CONSTRAINT comms_db_flexschema_pkey PRIMARY KEY (id);


--
-- Name: comms_db_flexschemafield comms_db_flexschemafield_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_flexschemafield
    ADD CONSTRAINT comms_db_flexschemafield_pkey PRIMARY KEY (id);


--
-- Name: comms_db_form comms_db_form_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_form
    ADD CONSTRAINT comms_db_form_name_key UNIQUE (name);


--
-- Name: comms_db_form comms_db_form_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_form
    ADD CONSTRAINT comms_db_form_pkey PRIMARY KEY (id);


--
-- Name: comms_db_industry comms_db_industry_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_industry
    ADD CONSTRAINT comms_db_industry_name_key UNIQUE (name);


--
-- Name: comms_db_industry comms_db_industry_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_industry
    ADD CONSTRAINT comms_db_industry_pkey PRIMARY KEY (id);


--
-- Name: comms_db_partner comms_db_partner_contact_email_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_partner
    ADD CONSTRAINT comms_db_partner_contact_email_key UNIQUE (contact_email);


--
-- Name: comms_db_partner comms_db_partner_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_partner
    ADD CONSTRAINT comms_db_partner_name_key UNIQUE (name);


--
-- Name: comms_db_partner comms_db_partner_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_partner
    ADD CONSTRAINT comms_db_partner_pkey PRIMARY KEY (id);


--
-- Name: comms_db_priority comms_db_priority_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_priority
    ADD CONSTRAINT comms_db_priority_name_key UNIQUE (name);


--
-- Name: comms_db_priority comms_db_priority_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_priority
    ADD CONSTRAINT comms_db_priority_pkey PRIMARY KEY (id);


--
-- Name: comms_db_review comms_db_review_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_review
    ADD CONSTRAINT comms_db_review_pkey PRIMARY KEY (id);


--
-- Name: comms_db_risklevel comms_db_risklevel_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_risklevel
    ADD CONSTRAINT comms_db_risklevel_name_key UNIQUE (name);


--
-- Name: comms_db_risklevel comms_db_risklevel_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_risklevel
    ADD CONSTRAINT comms_db_risklevel_pkey PRIMARY KEY (id);


--
-- Name: comms_db_role comms_db_role_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_role
    ADD CONSTRAINT comms_db_role_name_key UNIQUE (name);


--
-- Name: comms_db_role comms_db_role_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_role
    ADD CONSTRAINT comms_db_role_pkey PRIMARY KEY (id);


--
-- Name: comms_db_rule comms_db_rule_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_rule
    ADD CONSTRAINT comms_db_rule_name_key UNIQUE (name);


--
-- Name: comms_db_rule comms_db_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_rule
    ADD CONSTRAINT comms_db_rule_pkey PRIMARY KEY (id);


--
-- Name: comms_db_status comms_db_status_name_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_status
    ADD CONSTRAINT comms_db_status_name_key UNIQUE (name);


--
-- Name: comms_db_status comms_db_status_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_status
    ADD CONSTRAINT comms_db_status_pkey PRIMARY KEY (id);


--
-- Name: comms_db_submission comms_db_submission_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_pkey PRIMARY KEY (id);


--
-- Name: comms_db_thread comms_db_thread_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_thread
    ADD CONSTRAINT comms_db_thread_pkey PRIMARY KEY (id);


--
-- Name: comms_db_threadmessage comms_db_threadmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_threadmessage
    ADD CONSTRAINT comms_db_threadmessage_pkey PRIMARY KEY (id);


--
-- Name: comms_db_user comms_db_user_email_key; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user
    ADD CONSTRAINT comms_db_user_email_key UNIQUE (email);


--
-- Name: comms_db_user_groups comms_db_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_groups
    ADD CONSTRAINT comms_db_user_groups_pkey PRIMARY KEY (id);


--
-- Name: comms_db_user_groups comms_db_user_groups_user_id_group_id_ba4bb674_uniq; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_groups
    ADD CONSTRAINT comms_db_user_groups_user_id_group_id_ba4bb674_uniq UNIQUE (user_id, group_id);


--
-- Name: comms_db_user comms_db_user_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user
    ADD CONSTRAINT comms_db_user_pkey PRIMARY KEY (id);


--
-- Name: comms_db_user_user_permissions comms_db_user_user_permi_user_id_permission_id_756b1042_uniq; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_user_permissions
    ADD CONSTRAINT comms_db_user_user_permi_user_id_permission_id_756b1042_uniq UNIQUE (user_id, permission_id);


--
-- Name: comms_db_user_user_permissions comms_db_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_user_permissions
    ADD CONSTRAINT comms_db_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: comms_db_action_name_9a3ef3e1_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_action_name_9a3ef3e1_like ON public.comms_db_action USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_attachement_content_type_id_8e5fcf71; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_attachement_content_type_id_8e5fcf71 ON public.comms_db_attachement USING btree (content_type_id);


--
-- Name: comms_db_attachement_creator_id_1326e9c3; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_attachement_creator_id_1326e9c3 ON public.comms_db_attachement USING btree (creator_id);


--
-- Name: comms_db_attachement_submission_id_1629a9e5; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_attachement_submission_id_1629a9e5 ON public.comms_db_attachement USING btree (submission_id);


--
-- Name: comms_db_compliancerisk_risk_level_id_a107306f; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_compliancerisk_risk_level_id_a107306f ON public.comms_db_compliancerisk USING btree (risk_level_id);


--
-- Name: comms_db_contenttype_name_33370392_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_contenttype_name_33370392_like ON public.comms_db_contenttype USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_denialreason_name_8a79f441_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_denialreason_name_8a79f441_like ON public.comms_db_denialreason USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_distributionchannel_name_690b674d_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_distributionchannel_name_690b674d_like ON public.comms_db_distributionchannel USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_flexschema_name_04b60a64_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_flexschema_name_04b60a64_like ON public.comms_db_flexschema USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_flexschemafield_schema_id_c938bb15; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_flexschemafield_schema_id_c938bb15 ON public.comms_db_flexschemafield USING btree (schema_id);


--
-- Name: comms_db_form_name_87827640_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_form_name_87827640_like ON public.comms_db_form USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_form_schema_id_8ae89701; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_form_schema_id_8ae89701 ON public.comms_db_form USING btree (schema_id);


--
-- Name: comms_db_industry_name_eabf18b4_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_industry_name_eabf18b4_like ON public.comms_db_industry USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_partner_contact_email_dd46ad53_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_partner_contact_email_dd46ad53_like ON public.comms_db_partner USING btree (contact_email varchar_pattern_ops);


--
-- Name: comms_db_partner_industry_id_e78a7bfc; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_partner_industry_id_e78a7bfc ON public.comms_db_partner USING btree (industry_id);


--
-- Name: comms_db_partner_name_c47323e9_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_partner_name_c47323e9_like ON public.comms_db_partner USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_priority_name_7055af09_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_priority_name_7055af09_like ON public.comms_db_priority USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_review_reviewer_id_681ffe00; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_review_reviewer_id_681ffe00 ON public.comms_db_review USING btree (reviewer_id);


--
-- Name: comms_db_review_submission_id_91f140dc; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_review_submission_id_91f140dc ON public.comms_db_review USING btree (submission_id);


--
-- Name: comms_db_risklevel_name_c11e0fbb_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_risklevel_name_c11e0fbb_like ON public.comms_db_risklevel USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_role_name_357170aa_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_role_name_357170aa_like ON public.comms_db_role USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_rule_name_88865f4d_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_rule_name_88865f4d_like ON public.comms_db_rule USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_status_name_7893f8a6_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_status_name_7893f8a6_like ON public.comms_db_status USING btree (name varchar_pattern_ops);


--
-- Name: comms_db_submission_content_type_id_ac30bb2b; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_content_type_id_ac30bb2b ON public.comms_db_submission USING btree (content_type_id);


--
-- Name: comms_db_submission_creator_id_b2d7133c; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_creator_id_b2d7133c ON public.comms_db_submission USING btree (creator_id);


--
-- Name: comms_db_submission_industry_id_d09a5cc1; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_industry_id_d09a5cc1 ON public.comms_db_submission USING btree (industry_id);


--
-- Name: comms_db_submission_partner_id_fd188ccf; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_partner_id_fd188ccf ON public.comms_db_submission USING btree (partner_id);


--
-- Name: comms_db_submission_priority_id_0a1a61af; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_priority_id_0a1a61af ON public.comms_db_submission USING btree (priority_id);


--
-- Name: comms_db_submission_schema_id_756e240c; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_schema_id_756e240c ON public.comms_db_submission USING btree (schema_id);


--
-- Name: comms_db_submission_status_id_30c277c8; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_submission_status_id_30c277c8 ON public.comms_db_submission USING btree (status_id);


--
-- Name: comms_db_thread_submission_id_5c40fee2; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_thread_submission_id_5c40fee2 ON public.comms_db_thread USING btree (submission_id);


--
-- Name: comms_db_threadmessage_thread_id_e4c523ef; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_threadmessage_thread_id_e4c523ef ON public.comms_db_threadmessage USING btree (thread_id);


--
-- Name: comms_db_user_email_e1fe47c2_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_user_email_e1fe47c2_like ON public.comms_db_user USING btree (email varchar_pattern_ops);


--
-- Name: comms_db_user_groups_group_id_7b44474f; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_user_groups_group_id_7b44474f ON public.comms_db_user_groups USING btree (group_id);


--
-- Name: comms_db_user_groups_user_id_72b84032; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_user_groups_user_id_72b84032 ON public.comms_db_user_groups USING btree (user_id);


--
-- Name: comms_db_user_user_permissions_permission_id_14874e44; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_user_user_permissions_permission_id_14874e44 ON public.comms_db_user_user_permissions USING btree (permission_id);


--
-- Name: comms_db_user_user_permissions_user_id_e8719a7e; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX comms_db_user_user_permissions_user_id_e8719a7e ON public.comms_db_user_user_permissions USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: comms_admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_attachement comms_db_attachement_content_type_id_8e5fcf71_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_attachement
    ADD CONSTRAINT comms_db_attachement_content_type_id_8e5fcf71_fk_comms_db_ FOREIGN KEY (content_type_id) REFERENCES public.comms_db_contenttype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_attachement comms_db_attachement_creator_id_1326e9c3_fk_comms_db_user_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_attachement
    ADD CONSTRAINT comms_db_attachement_creator_id_1326e9c3_fk_comms_db_user_id FOREIGN KEY (creator_id) REFERENCES public.comms_db_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_attachement comms_db_attachement_submission_id_1629a9e5_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_attachement
    ADD CONSTRAINT comms_db_attachement_submission_id_1629a9e5_fk_comms_db_ FOREIGN KEY (submission_id) REFERENCES public.comms_db_submission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_compliancerisk comms_db_compliancer_risk_level_id_a107306f_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_compliancerisk
    ADD CONSTRAINT comms_db_compliancer_risk_level_id_a107306f_fk_comms_db_ FOREIGN KEY (risk_level_id) REFERENCES public.comms_db_risklevel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_compliancerisk comms_db_compliancer_submission_id_56c67165_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_compliancerisk
    ADD CONSTRAINT comms_db_compliancer_submission_id_56c67165_fk_comms_db_ FOREIGN KEY (submission_id) REFERENCES public.comms_db_submission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_flexschemafield comms_db_flexschemaf_schema_id_c938bb15_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_flexschemafield
    ADD CONSTRAINT comms_db_flexschemaf_schema_id_c938bb15_fk_comms_db_ FOREIGN KEY (schema_id) REFERENCES public.comms_db_flexschema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_form comms_db_form_schema_id_8ae89701_fk_comms_db_flexschema_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_form
    ADD CONSTRAINT comms_db_form_schema_id_8ae89701_fk_comms_db_flexschema_id FOREIGN KEY (schema_id) REFERENCES public.comms_db_flexschema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_partner comms_db_partner_industry_id_e78a7bfc_fk_comms_db_industry_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_partner
    ADD CONSTRAINT comms_db_partner_industry_id_e78a7bfc_fk_comms_db_industry_id FOREIGN KEY (industry_id) REFERENCES public.comms_db_industry(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_review comms_db_review_reviewer_id_681ffe00_fk_comms_db_user_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_review
    ADD CONSTRAINT comms_db_review_reviewer_id_681ffe00_fk_comms_db_user_id FOREIGN KEY (reviewer_id) REFERENCES public.comms_db_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_review comms_db_review_submission_id_91f140dc_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_review
    ADD CONSTRAINT comms_db_review_submission_id_91f140dc_fk_comms_db_ FOREIGN KEY (submission_id) REFERENCES public.comms_db_submission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_content_type_id_ac30bb2b_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_content_type_id_ac30bb2b_fk_comms_db_ FOREIGN KEY (content_type_id) REFERENCES public.comms_db_contenttype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_creator_id_b2d7133c_fk_comms_db_user_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_creator_id_b2d7133c_fk_comms_db_user_id FOREIGN KEY (creator_id) REFERENCES public.comms_db_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_industry_id_d09a5cc1_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_industry_id_d09a5cc1_fk_comms_db_ FOREIGN KEY (industry_id) REFERENCES public.comms_db_industry(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_partner_id_fd188ccf_fk_comms_db_partner_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_partner_id_fd188ccf_fk_comms_db_partner_id FOREIGN KEY (partner_id) REFERENCES public.comms_db_partner(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_priority_id_0a1a61af_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_priority_id_0a1a61af_fk_comms_db_ FOREIGN KEY (priority_id) REFERENCES public.comms_db_priority(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_schema_id_756e240c_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_schema_id_756e240c_fk_comms_db_ FOREIGN KEY (schema_id) REFERENCES public.comms_db_flexschema(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_submission comms_db_submission_status_id_30c277c8_fk_comms_db_status_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_submission
    ADD CONSTRAINT comms_db_submission_status_id_30c277c8_fk_comms_db_status_id FOREIGN KEY (status_id) REFERENCES public.comms_db_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_thread comms_db_thread_submission_id_5c40fee2_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_thread
    ADD CONSTRAINT comms_db_thread_submission_id_5c40fee2_fk_comms_db_ FOREIGN KEY (submission_id) REFERENCES public.comms_db_submission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_threadmessage comms_db_threadmessage_thread_id_e4c523ef_fk_comms_db_thread_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_threadmessage
    ADD CONSTRAINT comms_db_threadmessage_thread_id_e4c523ef_fk_comms_db_thread_id FOREIGN KEY (thread_id) REFERENCES public.comms_db_thread(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_user_groups comms_db_user_groups_group_id_7b44474f_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_groups
    ADD CONSTRAINT comms_db_user_groups_group_id_7b44474f_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_user_groups comms_db_user_groups_user_id_72b84032_fk_comms_db_user_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_groups
    ADD CONSTRAINT comms_db_user_groups_user_id_72b84032_fk_comms_db_user_id FOREIGN KEY (user_id) REFERENCES public.comms_db_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_user_user_permissions comms_db_user_user_p_permission_id_14874e44_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_user_permissions
    ADD CONSTRAINT comms_db_user_user_p_permission_id_14874e44_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comms_db_user_user_permissions comms_db_user_user_p_user_id_e8719a7e_fk_comms_db_; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.comms_db_user_user_permissions
    ADD CONSTRAINT comms_db_user_user_p_user_id_e8719a7e_fk_comms_db_ FOREIGN KEY (user_id) REFERENCES public.comms_db_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_comms_db_user_id; Type: FK CONSTRAINT; Schema: public; Owner: comms_admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_comms_db_user_id FOREIGN KEY (user_id) REFERENCES public.comms_db_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO comms_admin;


--
-- PostgreSQL database dump complete
--

